spring.datasource.url=jdbc:postgresql://localhost:5432/bookRights
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver


# Server port
server.port=8080

## Create tables automatically based on entities
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true

# Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.baseline-on-migrate=true


secret.key=wV7k9pF2mTqY4cH8sL1bR6nX3vJ0zA5dK9uQ2eM7yP8fS1gL

